include("../core/header.jl")
using LaTeXStrings

data = CSV.read("lyapunov/soft_lyapunov.csv", DataFrame)
rcvd = CSV.read("lyapunov/soft_lyapunov_rcvd.csv", DataFrame)
plot(xlabel = L"d", ylabel = L"\lambda", legend = :none, title = "Lyapunov spectrum of soft impact model")
plot!(data.bp, data.λ1, color = :black)
plot!(data.bp, data.λ2, color = :black)
plot!(data.bp, data.λ3, color = :black)
scatter!(rcvd.bp, rcvd.λ1, color = :red, shape = :x, ms = 1)
scatter!(rcvd.bp, rcvd.λ2, color = :red, shape = :x, ms = 1)
scatter!(rcvd.bp, rcvd.λ3, color = :red, shape = :x, ms = 1)
png("soft_lyapunov")


data = CSV.read("lyapunov/hrnm_lyapunov.csv", DataFrame)
rcvd = CSV.read("lyapunov/hrnm_lyapunov_rcvd.csv", DataFrame)
plot(xlabel = L"f", ylabel = L"\lambda", legend = :none, title = "Lyapunov spectrum of HR model")
plot!(data.bp, data.λ1, color = :black)
plot!(data.bp, data.λ2, color = :black)
plot!(data.bp, data.λ3, color = :black)
scatter!(rcvd.bp, rcvd.λ1, color = :red, shape = :x, ms = 1)
scatter!(rcvd.bp, rcvd.λ2, color = :red, shape = :x, ms = 1)
scatter!(rcvd.bp, rcvd.λ3, color = :red, shape = :x, ms = 1)
png("hrnm_lyapunov")
